1.33.0 run responsible
tonlabs/ever-sdk pull request #685
Opened 2022-04-07 08:51 UTC by melsomino

2022-04-19 09:11 UTC, AlexeyVavilin requested changes

2022-04-19 09:11 UTC, AlexeyVavilin commented on ton_client/src/abi/decode_message.rs
> +                let receiver_func_id = body.get_next_u32().map_err(|err| {
Use `ton_abi::Function::decode_output_id`

2022-04-19 09:11 UTC, AlexeyVavilin commented on ton_client/src/abi/decode_message.rs
> +                    let tokens = TokenValue::decode_params(
Use `responsible.function.decode_output`. I disabled function id check for internal output messages

2022-04-20 18:49 UTC, melsomino commented on ton_client/src/abi/decode_message.rs
> +                let receiver_func_id = body.get_next_u32().map_err(|err| {
I can't because decode_output_id doesn't move cursor

2022-04-20 19:05 UTC, merged