NEW: `create_crypto_box` optimisation.
tonlabs/ever-sdk pull request #868
Opened 2022-09-09 10:41 UTC by melsomino

When user creates crypto box, SDK encrypts provided secret information using provided password
  and salt.
  When SDK encrypts secret, it derives encryption key from password and salt using `scrypt`
  function which takes a lot of CPU time (about 1 second).
  So when the user creates many crypto boxes using same password and salt, it is required a lot
  of time (about 12 seconds for 10 crypto boxes).
  With optimisations introduced in this version the SDK caches mapping (password+salt => encryption key)
  for approximately 2 seconds.
  So when the user creates many crypto boxes using same password and salt, it is required only
  a 1.2 seconds for 10 crypto boxes.

2022-09-11 20:13 UTC, elasticLove1 approved these changes

2022-09-12 14:50 UTC, AlexeyVavilin requested changes

2022-09-12 14:50 UTC, AlexeyVavilin commented on ton_client/src/crypto/boxes/crypto_box/derived_keys.rs
> +                println!("use cached key");
Remove print or replace with trace logging

2022-09-12 14:50 UTC, AlexeyVavilin commented on ton_client/src/crypto/boxes/crypto_box/derived_keys.rs
> +        if let Some(existing) = { self.write_cache().touch(&hash).map(|x| x.clone()) } {
Are curly braces needed here? Guard is dropped after experssion is executed

2022-09-12 14:50 UTC, AlexeyVavilin commented on CHANGELOG.md
> +- Some enum types ware not properly presented in api.json (some types that use serde(content="value"))
Wrong fix

2022-09-12 20:51 UTC, elasticLove1 commented on CHANGELOG.md
> +- Some enum types ware not properly presented in api.json (some types that use serde(content="value"))
I fixed the fix)))

2022-09-13 06:59 UTC, closed without merging