Upped version of dependencies
tonlabs/ever-sdk pull request #984
Opened 2023-04-06 13:03 UTC by sv-91

2023-04-06 13:39 UTC, elasticLove1 approved these changes

2023-04-18 13:25 UTC, AlexeyVavilin requested changes
See comment and also describe changes in changelog

2023-04-18 13:25 UTC, AlexeyVavilin commented on ton_client/Cargo.toml
> +version = '1.44.0'
Don't change versions. Leave 1.43.0 in all tomls

2023-04-18 13:41 UTC, AlexeyVavilin approved these changes

2023-04-18 13:41 UTC, merged